# This file is distributed under the same license as the Django package.
#
# Translators:
# Jannis Leidel <jannis@leidel.info>, 2011
# Shinya Okano <tokibito@gmail.com>, 2013-2014
msgid ""
msgstr ""
"Project-Id-Version: django\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2014-05-20 12:20+0200\n"
"PO-Revision-Date: 2014-06-28 14:23+0000\n"
"Last-Translator: Shinya Okano <tokibito@gmail.com>\n"
"Language-Team: Japanese (http://www.transifex.com/projects/p/django/language/"
"ja/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: contrib/auth/admin.py:44
msgid "Personal info"
msgstr "個人情報"

#: contrib/auth/admin.py:45
msgid "Permissions"
msgstr "パーミッション"

#: contrib/auth/admin.py:47
msgid "Important dates"
msgstr "重要な日程"

#: contrib/auth/admin.py:134
msgid "Password changed successfully."
msgstr "パスワードを変更しました"

#: contrib/auth/admin.py:145
#, python-format
msgid "Change password: %s"
msgstr "パスワードの変更: %s"

#: contrib/auth/apps.py:10
msgid "Authentication and Authorization"
msgstr "認証と認可"

#: contrib/auth/forms.py:37 contrib/auth/tests/test_forms.py:316
#: contrib/auth/tests/test_forms.py:321 contrib/auth/tests/test_forms.py:504
msgid "No password set."
msgstr "パスワードは設定されませんでした。"

#: contrib/auth/forms.py:43 contrib/auth/tests/test_forms.py:326
#: contrib/auth/tests/test_forms.py:332
msgid "Invalid password format or unknown hashing algorithm."
msgstr "無効なパスワードか不明なハッシュアルゴリズムです。"

#: contrib/auth/forms.py:76
msgid "A user with that username already exists."
msgstr "同じユーザー名が既に登録済みです。"

#: contrib/auth/forms.py:77 contrib/auth/forms.py:285
#: contrib/auth/forms.py:349
msgid "The two password fields didn't match."
msgstr "確認用パスワードが一致しません。"

#: contrib/auth/forms.py:79 contrib/auth/forms.py:129
msgid "Username"
msgstr "ユーザー名"

#: contrib/auth/forms.py:81 contrib/auth/forms.py:130
#: contrib/auth/models.py:368
msgid "Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only."
msgstr ""
"この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で30文字以下にし"
"てください。"

#: contrib/auth/forms.py:84 contrib/auth/forms.py:133
msgid "This value may contain only letters, numbers and @/./+/-/_ characters."
msgstr "半角の英数字および次の記号 @/./+/-/_ 以外は使用できません。"

#: contrib/auth/forms.py:86 contrib/auth/forms.py:135
#: contrib/auth/forms.py:163 contrib/auth/forms.py:351
msgid "Password"
msgstr "パスワード"

#: contrib/auth/forms.py:88
msgid "Password confirmation"
msgstr "パスワードの確認"

#: contrib/auth/forms.py:90
msgid "Enter the same password as above, for verification."
msgstr "確認のため、再度パスワードを入力してください。"

#: contrib/auth/forms.py:136
msgid ""
"Raw passwords are not stored, so there is no way to see this user's "
"password, but you can change the password using <a href=\"password/\">this "
"form</a>."
msgstr ""
"生のパスワードが格納されていないので、このユーザーのパスワードは参照できませ"
"んが、 <a href=\"password/\">このフォーム</a> を使用してパスワードを変更でき"
"ます 。"

#: contrib/auth/forms.py:166
#, python-format
msgid ""
"Please enter a correct %(username)s and password. Note that both fields may "
"be case-sensitive."
msgstr ""
"正しい%(username)sとパスワードを入力してください。どちらのフィールドも大文字"
"と小文字は区別されます。"

#: contrib/auth/forms.py:168
msgid "This account is inactive."
msgstr "アカウントが無効です。"

#: contrib/auth/forms.py:231
msgid "Email"
msgstr "メールアドレス"

#: contrib/auth/forms.py:287
msgid "New password"
msgstr "新しいパスワード"

#: contrib/auth/forms.py:289
msgid "New password confirmation"
msgstr "新しいパスワード(確認用)"

#: contrib/auth/forms.py:320
msgid "Your old password was entered incorrectly. Please enter it again."
msgstr "元のパスワードが間違っています。もう一度入力してください。"

#: contrib/auth/forms.py:323
msgid "Old password"
msgstr "元のパスワード"

#: contrib/auth/forms.py:353
msgid "Password (again)"
msgstr "パスワード(確認用)"

#: contrib/auth/hashers.py:252 contrib/auth/hashers.py:335
#: contrib/auth/hashers.py:383 contrib/auth/hashers.py:411
#: contrib/auth/hashers.py:444 contrib/auth/hashers.py:477
#: contrib/auth/hashers.py:511
msgid "algorithm"
msgstr "アルゴリズム"

#: contrib/auth/hashers.py:253
msgid "iterations"
msgstr "イテレーション"

#: contrib/auth/hashers.py:254 contrib/auth/hashers.py:337
#: contrib/auth/hashers.py:384 contrib/auth/hashers.py:412
#: contrib/auth/hashers.py:512
msgid "salt"
msgstr "ソルト"

#: contrib/auth/hashers.py:255 contrib/auth/hashers.py:385
#: contrib/auth/hashers.py:413 contrib/auth/hashers.py:445
#: contrib/auth/hashers.py:478 contrib/auth/hashers.py:513
msgid "hash"
msgstr "ハッシュ"

#: contrib/auth/hashers.py:336
msgid "work factor"
msgstr "ワークファクター"

#: contrib/auth/hashers.py:338
msgid "checksum"
msgstr "チェックサム"

#: contrib/auth/models.py:63 contrib/auth/models.py:112
msgid "name"
msgstr "名前"

#: contrib/auth/models.py:65
msgid "codename"
msgstr "コード名"

#: contrib/auth/models.py:69
msgid "permission"
msgstr "パーミッション"

#: contrib/auth/models.py:70 contrib/auth/models.py:114
msgid "permissions"
msgstr "パーミッション"

#: contrib/auth/models.py:119
msgid "group"
msgstr "グループ"

#: contrib/auth/models.py:120 contrib/auth/models.py:293
msgid "groups"
msgstr "グループ"

#: contrib/auth/models.py:192
msgid "password"
msgstr "パスワード"

#: contrib/auth/models.py:193
msgid "last login"
msgstr "最終ログイン"

#: contrib/auth/models.py:290
msgid "superuser status"
msgstr "スーパーユーザー権限"

#: contrib/auth/models.py:291
msgid ""
"Designates that this user has all permissions without explicitly assigning "
"them."
msgstr "全ての権限を持っているとみなされます。"

#: contrib/auth/models.py:294
msgid ""
"The groups this user belongs to. A user will get all permissions granted to "
"each of his/her group."
msgstr ""
"このユーザーが所属するグループ。ユーザーはグループのそれぞれに付与されている"
"すべての権限を持ちます。"

#: contrib/auth/models.py:299
msgid "user permissions"
msgstr "ユーザーパーミッション"

#: contrib/auth/models.py:300
msgid "Specific permissions for this user."
msgstr "このユーザーの持つ権限です。"

#: contrib/auth/models.py:367
msgid "username"
msgstr "ユーザー名"

#: contrib/auth/models.py:371
msgid "Enter a valid username."
msgstr "有効なメールアドレスを入力してください。"

#: contrib/auth/models.py:373
msgid "first name"
msgstr "名"

#: contrib/auth/models.py:374
msgid "last name"
msgstr "姓"

#: contrib/auth/models.py:375
msgid "email address"
msgstr "メールアドレス"

#: contrib/auth/models.py:376
msgid "staff status"
msgstr "スタッフ権限"

#: contrib/auth/models.py:377
msgid "Designates whether the user can log into this admin site."
msgstr "ユーザーが管理サイトにログイン可能かどうかを示します。"

#: contrib/auth/models.py:379
msgid "active"
msgstr "有効"

#: contrib/auth/models.py:380
msgid ""
"Designates whether this user should be treated as active. Unselect this "
"instead of deleting accounts."
msgstr ""
"ユーザーがアクティブかどうかを示します。アカウントを消す代わりに選択を解除し"
"てください。"

#: contrib/auth/models.py:382
msgid "date joined"
msgstr "登録日"

#: contrib/auth/models.py:390
msgid "user"
msgstr "ユーザー"

#: contrib/auth/models.py:391
msgid "users"
msgstr "ユーザー"

#: contrib/auth/templates/registration/password_reset_subject.txt:2
#, python-format
msgid "Password reset on %(site_name)s"
msgstr "%(site_name)s のパスワードリセット"

#: contrib/auth/tests/test_forms.py:387
msgid "Enter a valid email address."
msgstr "有効なメールアドレスを入力してください。"

#: contrib/auth/views.py:92
msgid "Logged out"
msgstr "ログアウト"

#: contrib/auth/views.py:169
msgid "Password reset"
msgstr "パスワードをリセット"

#: contrib/auth/views.py:181
msgid "Password reset successful"
msgstr "パスワードをリセットしました"

#: contrib/auth/views.py:216
msgid "Enter new password"
msgstr "新しいパスワードを入力してください"

#: contrib/auth/views.py:227
msgid "Password reset unsuccessful"
msgstr "パスワードのリセットに失敗しました"

#: contrib/auth/views.py:244
msgid "Password reset complete"
msgstr "パスワードがリセットされました"

#: contrib/auth/views.py:278
msgid "Password change"
msgstr "パスワードの変更"

#: contrib/auth/views.py:291
msgid "Password change successful"
msgstr "パスワードを変更しました"
